before_install:
   - wget https://s3.amazonaws.com/rebar3/rebar3
   - chmod u+x ./rebar3
install: "true"
language: erlang
sudo: false
otp_release:
  - 18.2.1
  - 17.5
script:
  - ./rebar3 do xref,eunit,dialyze
  - ./rebar3 coveralls send
